version: "3.8"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.api
      args:
        ENV_FILE: .env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
