version: "3.8"
services:
  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.api
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile.ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
#volumes:
#  mongo-data:
