export const trails = [
  {
    name: "Grouse Grind",
    latitude: 49.371206,
    longitude: -123.098424,
    photoUrl: "https://explore-mag.com/wp-content/uploads/2024/03/Grouse-Grind_327942_max.png",
    city: "North Vancouver, BC",
    description: "A steep and challenging trail often called 'Mother Nature's Stairmaster', popular for fitness enthusiasts.",
    elevation: "853m",
    weather: "",
    tags: ["fitness", "steep", "stairs"],
    difficulty: "Hard",
    distance: "2.9km"
  },
  {
    name: "St Marks Summit",
    latitude: 49.42802,
    longitude: -123.20133,
    photoUrl: "https://rockwoodadventures.com/wp-content/uploads/2021/04/1.-Lead-Pic-St-Marks-Summit-Old-Bags-New-Tricks.jpg",
    city: "Cypress Mountain, West Vancouver, BC",
    description: "A rewarding hike with stunning views of Howe Sound and the surrounding mountains.",
    elevation: "460m",
    weather: "",
    tags: ["viewpoint", "moderate", "summit"],
    difficulty: "Moderate",
    distance: "11km"
  },
  {
    name: "Dog Mountain",
    latitude: 49.37373,
    longitude: -122.97043,
    photoUrl: "https://i0.wp.com/besthikesbc.ca/wp-content/uploads/2021/03/DSC02029-Pano.jpg?fit=2048%2C1032&ssl=1",
    city: "Mount Seymour, North Vancouver, BC",
    description: "An easy trail with a panoramic view of Vancouver from the top.",
    elevation: "150m",
    weather: "",
    tags: ["easy", "view", "family"],
    difficulty: "Easy",
    distance: "5km"
  },
  {
    name: "Lynn Loop",
    latitude: 49.358,
    longitude: -123.000,
    photoUrl: "https://www.vancouvertrails.com/images/photos/lynn-loop-4.jpg",
    city: "Lynn Headwaters, North Vancouver, BC",
    description: "A peaceful forest loop following the banks of Lynn Creek.",
    elevation: "100m",
    weather: "",
    tags: ["forest", "loop", "creek"],
    difficulty: "Easy",
    distance: "5.1km"
  },
  {
    name: "Quarry Rock",
    latitude: 49.3269,
    longitude: -122.9487,
    photoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp_XqyUSj_h05-vQWmmoWGLqAfE5bgwGzoNg&s",
    city: "Deep Cove, North Vancouver, BC",
    description: "A short hike to a popular viewpoint over Indian Arm and Deep Cove.",
    elevation: "100m",
    weather: "",
    tags: ["short", "viewpoint", "popular"],
    difficulty: "Easy",
    distance: "3.8km"
  },
  {
    name: "Capilano Pacific",
    latitude: 49.354,
    longitude: -123.114,
    photoUrl: "https://www.vancouvertrails.com/images/photos/capilano-pacific-trail-6.jpg",
    city: "West Vancouver to Capilano Dam, BC",
    description: "A scenic riverside trail that ends at the historic Capilano Dam.",
    elevation: "180m",
    weather: "",
    tags: ["riverside", "historic", "long"],
    difficulty: "Moderate",
    distance: "7.5km"
  },
  {
    name: "Norvan Falls",
    latitude: 49.358,
    longitude: -123.000,
    photoUrl: "https://www.vancouvertrails.com/images/hikes-small/norvan-falls.jpg",
    city: "Lynn Headwaters, North Vancouver, BC",
    description: "A long forested trail ending at a beautiful waterfall, suitable for all levels.",
    elevation: "195m",
    weather: "",
    tags: ["waterfall", "long", "forest"],
    difficulty: "Moderate",
    distance: "14km"
  },
  {
    name: "Eagle Bluffs",
    latitude: 49.395,
    longitude: -123.201,
    photoUrl: "https://i0.wp.com/besthikesbc.ca/wp-content/uploads/2020/12/DSC00354.jpg?fit=2048%2C1197&ssl=1",
    city: "Cypress Mountain, West Vancouver, BC",
    description: "A moderately difficult hike offering panoramic views of Vancouver and Howe Sound.",
    elevation: "350m",
    weather: "",
    tags: ["bluffs", "scenic", "view"],
    difficulty: "Moderate",
    distance: "8km"
  },
  {
    name: "Velodrome Trail",
    latitude: 49.281,
    longitude: -122.926,
    photoUrl: "https://www.vancouvertrails.com/images/photos/velodrome-trail-1.jpg",
    city: "Burnaby Mountain, Burnaby, BC",
    description: "A short but steep trail up Burnaby Mountain, also known as Burnaby's Grouse Grind.",
    elevation: "240m",
    weather: "",
    tags: ["steep", "burnaby", "short"],
    difficulty: "Hard",
    distance: "1.3km"
  },
  {
    name: "Pacific Spirit Loop",
    latitude: 49.260,
    longitude: -123.254,
    photoUrl: "https://www.outdoorfam.ca/wp-content/uploads/2022/04/img_5012.jpg",
    city: "Pacific Spirit Park, Vancouver, BC",
    description: "A flat loop trail through peaceful coastal rainforest near UBC.",
    elevation: "60m",
    weather: "",
    tags: ["flat", "forest", "easy"],
    difficulty: "Easy",
    distance: "10km"
  }
];

// module.exports = trails;
